### ISSUE TITLE
Technical data tab in question landing

### ISSUE THREAD

**Issue by ailopezglez** [decidim/decidim-module-consultations#13]
This functionality is not supported in the core. @xabier , we should see how we can approach it

**Comment by xabier** [comment]
sorry @ailopezglez I am not sure I understand this feature, the title is to short :smile:

**Comment by ailopezglez** [comment]
Sorry, it's true that it's not clear. 
We have begun to discuss it in issue #1 
The problem is the generic  consultation data, in the new design is divided into two "tabs": information tab y technical data.
Decidim doesn't allow to divide the generic information in two tabs. All the information has to be in the information tab

**Comment by xabier** [comment]
mmmm I see... @htmlboy any ideas?

**Comment by htmlboy** [comment]
Yes, the idea is to create a new tab that contains the extended information, while keeping a brief introduction in the home-of-the-consultation-page. My  first understanding was to reuse the information page (as I understand, there can be more than one information page per process), while developing some new information modules on it. Isn't this something we could do?

**Comment by xabier** [comment]
@ailopezglez we need not develop anything new, what @htmlboy proposes is to unload the main page of the consultation-question to critical information (via config panel forms) and to call the Page component from the admin panel to include additional information as a "Ficha tecnica"

**Comment by ailopezglez** [comment]
@htmlboy @xabier Unless the core has developed something new, can only be one page of generic information per process
One option could be to structure the information in two different sections in the same page

**Comment by jsperezg** [comment]
@xabier I see several problems in @htmlboy suggestion:

* Generating a complex html that follows the Decidim UX conventions on the fly every time that the question changes will be:
  * Time expensive in terms of development resources.
  * Not accurate.
  * Extremely hard to test.

Additionally:
* Any change on decidim's layout will supose a completelly rewrite of this feature.
* Once the feature is finished, maintaining and extending it will be tough.

As I see the things right now, if we want to unclutter the information shown for the feature entry page we should implement a pagination mechanism inside the landing page. Trying to implement it on a higher level without the required resources and hooks in the core as I told before might be a tough task.

**Comment by xabier** [comment]
> @htmlboy @xabier Unless the core has developed something new, can only be one page of generic information per process

@ailopezglez , fortunately you are wrong :smile: processes allow to have as many information pages as you wish. so I think this is solved.

> As I see the things right now, if we want to unclutter the information shown for the feature entry page we should implement a pagination mechanism inside the landing page.

A simple solution to this problem is to just to have a limited character number on the fields that compose the main page. So we don't saturate it with information. I don't see any complex development changes required. We need to make consultations attractive and clear and @htmlboy 's proposal is trying to achieve this. He will also work on the html and he is the designer of the platform so I think we can trust him on doing something scalable, accurate and stable. 

Let's discuss the features one by one. Right now we need to review the mockups with the communication officers at Barcelona City Council and we will have more feedback. Regarding programing we should only worry, right now with the specific fields of the configuration interface and the components that need to be combined here. Does this sound ok?

**Comment by jsperezg** [comment]
@xabier You're right. It's not @ailopezglez fault, it's mine. I've checked the initiatives source and there is a way to add as many tabs as we need.

My fault, sorry for the noise.

**Comment by xabier** [comment]
No worries. Let's @htmlboy do the best design he can, assuming we need to innovate at the lowest programming cost. The we will try to do our best.

**Comment by jsperezg** [comment]
Thanks for your comprehension @xabier
